Repository ello/webapp, pull requests merged in 2018-05, with the labels that each got.

#433 Grid View: Post into category fix
  src/components/editor/CategoryPostSelector.js
  src/components/editor/PostActionBar.js
Labels: bug, please review, tiny

#415 Lightbox: Add to Grid View
  src/components/assets/Icons.css
  src/components/assets/Icons.js
  src/components/assets/ImageAsset.js
  src/components/light_box/LightBoxRenderables.js
  src/components/navbar/NavbarRenderables.js
  src/components/posts/PostRenderables.js
  src/components/posts/PostTools.css
  src/components/posts/PostTools.js
  src/components/regions/ImageRegion.js
  src/components/regions/RegionRenderables.js
  src/components/streams/StreamRenderables.js
  src/components/views/PostDetail.js
  src/containers/LightBoxContainer.js
  src/containers/NavbarContainer.js
  src/containers/PostContainer.js
  src/containers/PostLightBoxContainer.js
Labels: please review

#434 Post Editing: Show Current Category
  src/components/editor/BlockCollection.js
  src/components/editor/CategoryPostSelector.js
  src/components/editor/PostActionBar.js
Labels: please review

#436 Image Region: Disable Lightbox on cmd-click
  src/components/editor/CategoryPostSelector.js
  src/components/regions/ImageRegion.js
Labels: please review, tiny

#437 Heroes: Move Promo CTA
  src/components/heros/HeroParts.js
  src/components/heros/HeroRenderables.js
Labels: please review, tiny

#441 Post Category Fix: Allow clearing
  src/components/editor/CategoryPostSelector.js
Labels: please review, tiny

#440 Related Posts: Restore image links
  src/components/posts/PostRenderables.js
  src/components/regions/ImageRegion.js
  src/components/regions/RegionRenderables.js
Labels: please review, tiny

#442 Handle OrderedSet on post creation/deletion
  src/reducers/json.js
Labels: please review, tiny

#444 Change curation icon
  src/components/assets/Icons.js
  src/components/posts/PostHeader.css
  src/components/posts/PostRenderables.js
  src/components/posts/PostTools.js
Labels: please review

#445 Use graphql to populate editorials page.
  src/actions/editorials.js
  src/components/editorials/EditorialRenderables.js
  src/components/streams/StreamRenderables.js
  src/constants/action_types.js
  src/containers/EditorialContainer.js
  src/containers/PostStreamContainer.js
  src/containers/StreamContainer.js
  src/networking/api.js
  src/pages/EditorialPage.js
  src/queries/editorialStreamQueries.js
  src/queries/findPosts.js
  src/queries/fragments.js
  src/reducers/json.js
  src/reducers/v3_reducer.js
  src/sagas/v3_requester.js
  src/selectors/editorial.js
  src/selectors/routing.js
Labels: please review

#446 Re-structure Navbar
  src/components/assets/Avatar.js
  src/components/navbar/NavbarParts.js
  src/components/navbar/NavbarRenderables.js
  src/selectors/gui.js
Labels: please review

#447 Erroneous Text Formatter Fix
  src/components/artist_invites/ArtistInviteAdminRenderables.js
  src/components/categories/CategoryRenderables.js
  src/components/editor/CategoryPostSelector.js
  src/components/editor/PostActionBar.js
  src/components/heros/HeroRenderables.js
  src/components/light_box/LightBoxRenderables.js
  src/components/regions/ImageRegion.js
Labels: please review

#448 Artist Invite: Label Fix
  src/components/artist_invites/ArtistInviteAdminRenderables.js
Labels: please review, tiny

#449 This fixes the notifications drop down.
  src/components/navbar/NavbarRenderables.js
Labels: please review, tiny

#454 Parse path and url for external/internal editorial
  src/reducers/v3_reducer.js
Labels: please review, tiny

#453 Add new category user notifications
  src/components/notifications/NotificationRenderables.js
  src/containers/NotificationContainer.js
Labels: please review
