Repository ello/webapp, pull requests merged in 2018-04, with the labels that each got.

#418 Shop w/o recent
  src/actions/discover.js
  src/components/categories/CategoryRenderables.js
  src/selectors/page_headers.js
  src/selectors/routing.js
Labels: please review, tiny

#420 Check for subscribedIds before checking size.
  src/selectors/categories.js
Labels: please review, tiny

#419 Grid View: Fix Image Scaling
  src/components/streams/StreamRenderables.js
Labels: please review, tiny

#423 Comment Editor/Images: Remove Buy Button
  src/components/editor/BlockCollection.js
  src/components/editor/PostActionBar.js
  src/components/regions/ImageRegion.js
Labels: please review, tiny

#422 Post Detail: Pad empty related posts container
  src/components/views/PostDetail.js
  src/containers/StreamContainer.js
Labels: please review, tiny

#424 Fix navbar type mismatch warnings.
  src/components/navbar/NavbarParts.js
  src/components/navbar/NavbarRenderables.js
  src/containers/NavbarContainer.js
Labels: reviewed, tiny

#425 Artist Invite moderation on post detail
  src/actions/artist_invites.js
  src/actions/posts.js
  src/components/assets/Avatar.js
  src/components/posts/PostRenderables.js
  src/constants/action_types.js
  src/containers/PostContainer.js
  src/containers/PostDetailContainer.js
  src/queries/findPost.js
  src/queries/fragments.js
  src/reducers/json.js
  src/reducers/v3_reducer.js
  src/sagas/v3_requester.js
  src/selectors/post.js
  test/unit/actions/posts_test.js
Labels: please review

#417 Post to categories
  src/actions/editor.js
  src/actions/posts.js
  src/components/categories/CategoryRenderables.js
  src/components/editor/BlockCollection.js
  src/components/editor/CategoryPostSelector.js
  src/components/editor/Editor.css
  src/components/editor/Editor.js
  src/components/editor/PostActionBar.js
  src/constants/action_types.js
  src/helpers/editor_helper.js
  src/selectors/categories.js
  src/selectors/editor.js
  src/selectors/profile.js
  src/styles/jso.js
Labels: please review

#426 Discover: Sub-nav fix
  src/components/categories/CategoryRenderables.js
Labels: please review, tiny

#427 Editor in Grid: Fix for Reposts
  src/components/editor/BlockCollection.js
  src/components/editor/CategoryPostSelector.js
  src/components/editor/PostActionBar.js
  src/containers/PostContainer.js
Labels: please review

#428 Fix weird error that occurs without categories.
  src/selectors/categories.js
Labels: reviewed, tiny

#421 Trigger analytics events on category sub/unsub
  src/actions/profile.js
  src/constants/action_types.js
  src/containers/CategoryContainer.js
  src/containers/OnboardingCategoriesContainer.js
  src/reducers/json.js
  src/reducers/profile.js
  src/reducers/v3_reducer.js
  src/sagas/analytics.js
  src/sagas/requester.js
Labels: please review

#430 Adds category-post-selector events.
  src/components/editor/CategoryPostSelector.js
  src/components/editor/PostActionBar.js
Labels: please review

#429 Category Post tools
  src/actions/artist_invites.js
  src/actions/category_posts.js
  src/components/assets/Icons.js
  src/components/category_posts/CategoryPostRenderables.js
  src/components/editor/Editor.css
  src/components/posts/PostHeader.css
  src/components/posts/PostRenderables.js
  src/components/posts/PostTools.js
  src/components/tabs/CategoryTabBar.js
  src/components/views/PostDetail.js
  src/constants/mapping_types.js
  src/containers/CategoryPostHistoryContainer.js
  src/containers/PostContainer.js
  src/queries/fragments.js
  src/reducers/v3_reducer.js
  src/selectors/categories.js
  src/selectors/post.js
Labels: please review
