Repository ello/webapp, pull requests merged in 2018-07, with the labels that each got.

#465 Fix for “New Posts” Button
  src/components/navbar/NavbarParts.js
Labels: please review, tiny

#463 WIP - Category User Management: Profile Detail Page
  src/actions/gui.js
  src/actions/profile.js
  src/actions/user.js
  src/components/assets/Icons.css
  src/components/assets/Icons.js
  src/components/buttons/Buttons.js
  src/components/editor/CategoryPostSelector.js
  src/components/editor/PostActionBar.js
  src/components/forms/FilterSelectorControl.js
  src/components/forms/StatusMessage.js
  src/components/heros/HeroParts.js
  src/components/heros/HeroRenderables.js
  src/components/users/UserParts.css
  src/components/users/UserParts.js
  src/components/users/UserRenderables.js
  src/components/users/UserRolesRenderables.js
  src/constants/action_types.js
  src/constants/mapping_types.js
  src/containers/HeroProfileContainer.js
  src/containers/UserContainer.js
  src/containers/UserDetailRolesContainer.js
  src/networking/api.js
  src/queries/searchCategories.js
  src/reducers/gui.js
  src/reducers/json.js
  src/reducers/v3_reducer.js
  src/sagas/requester.js
  src/selectors/categories.js
  src/selectors/gui.js
  src/selectors/profile.js
  src/selectors/user.js
  test/unit/actions/gui_test.js
  test/unit/reducers/gui_test.js
Labels: please review, wip

#467 Fixes for Zero State Editor
  src/components/editor/BlockCollection.js
  src/components/editor/Editor.css
  src/components/editor/Editor.js
  src/components/editor/PostActionBar.js
  src/components/zeros/Zeros.js
Labels: please review, tiny

#468 Mobile Comment Box Margin Fix
  src/components/posts/PostRenderables.js
  src/components/streams/StreamContainer.css
Labels: please review, tiny

#469 Following via Graphql & Supporting "New Posts" button.
  src/actions/stream.js
  src/containers/FollowingContainer.js
  src/queries/postStreamQueries.js
  src/reducers/json.js
  src/reducers/v3_reducer.js
  test/unit/actions/stream_test.js
Labels: please review

#470 Fix post link loading.
  src/containers/PostDetailContainer.js
Labels: please review, tiny

#472 Lightbox: Add a key command for Loves
  src/constants/application_types.js
  src/containers/PostLightBoxContainer.js
Labels: please review, tiny

#466 Category User Management: Discover Sidebar
  src/actions/user.js
  src/components/assets/Icons.js
  src/components/categories/CategoryRenderables.js
  src/components/categories/CategoryRolesRenderables.js
  src/components/users/UserRenderables.js
  src/components/users/UserRolesRenderables.js
  src/constants/action_types.js
  src/containers/CategoryRolesContainer.js
  src/containers/UserContainer.js
  src/queries/userQuickSearchQuery.js
  src/reducers/json.js
  src/reducers/v3_reducer.js
  src/sagas/v3_requester.js
  src/selectors/profile.js
  src/selectors/user.js
  src/styles/jso.js
Labels: please review

#475 Confirm role removal on profile role admin
  src/components/users/UserRenderables.js
  src/components/users/UserRolesRenderables.js
  src/containers/UserDetailRolesContainer.js
Labels: please review

#474 Properly order (re)posts manually added to stream
  src/reducers/v3_reducer.js
Labels: please review, tiny

#476 Don't persist json in localstorage.
  src/main.js
Labels: please review, tiny

#477 Lightbox: Add the Feature Post tool
  src/components/light_box/LightBoxRenderables.js
  src/components/posts/PostTools.css
  src/components/posts/PostTools.js
  src/containers/PostLightBoxContainer.js
Labels: please review
